# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432
