# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs docker-compose
      - name: Run docker-compose
        run: |
          echo Run docker-compose
          docker-compose build
          docker-compose up -d
          docker ps

      # Perform tests
      - name: TestGetBeforePost
        run: docker run --network container:evidation_web_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:4567/
      - name: TestPost
        #run: docker run --network container:evidation_web_1 appropriate/curl -s --retry 10 --retry-connrefused --data "email=curl@gmail.com&name=curlname" http://localhost:4567/user/
        #run: docker run --network container:evidation_web_1 appropriate/curl -s --retry 10 --retry-connrefused --data "email=curl@gmail.com&name=curlname" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:4567/user/
        #run: docker run --network container:evidation_web_1 appropriate/curl -d "email=curl@gmail.com&name=curlname" -X POST http://localhost:4567/user/
        run: docker run --network container:evidation_web_1 appropriate/curl -s --retry 10 --retry-connrefused -d "email=curl@gmail.com&name=curlname" -X POST http://localhost:4567/user
      - name: testGetAfterPost
        run: docker run --network container:evidation_web_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:4567/
